//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHillsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsensores
    {
        public int id { get; set; }
        public string nomeComum { get; set; }
        public string nomeCientifico { get; set; }
        public string tempRecomendada { get; set; }
        public string umidRecomendada { get; set; }
        public string lumiRecomendada { get; set; }
    }
}
